name: "Generate a container guts manifest"
description: "Discover set of binaries on the PATH in a container"
inputs:
  image:
    description: Container Image
    required: true
  outfile:
    description: Output file (otherwise prints to screen)
    required: false

runs:
  using: "composite"
  steps:
   - name: Install Guts
     run: which guts || pip install git+https://github.com/singularityhub/guts@main
     shell: bash

   - name: Guts for ${{ inputs.image }}
     env:
       image: ${{ inputs.image }} 
       outfile: ${{ inputs.outfile }} 
     run: | 
        cmd="guts manifest"
        if [ "${outfile}" != "" ]; then
            cmd="${cmd} --outfile ${outfile}"
        fi
        cmd="${cmd} ${image}" 
        printf "${cmd}\n"
        ${cmd}
     shell: bash
