name: "Generate a container guts manifest"
description: "Discover set of binaries on the PATH in a container"
inputs:
  image:
    description: Container Image
    required: true
  outfile:
    description: Output file (otherwise prints to screen)
    required: false

runs:
  using: "composite"
  steps:
   - name: Guts for ${{ inputs.image }}
     env:
       image: ${{ inputs.image }} 
       outfile: ${{ inputs.outfile }} 
       action_path: ${{ github.action_path }}
     run: |
        cmd="python ${action_path}/scripts/prepare_manifests.py"
        if [ "${outfile}" != "" ]; then
            cmd="${cmd} --outfile ${outfile}"
        fi
        cmd="${cmd} ${image}" 
        printf "${cmd}\n"
     shell: bash
