name: Update Docs

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: "gh-pages"

      - name: Create conda environment
        run: conda create --quiet -c conda-forge --name guts

      - name: Generate Docs
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          root=$PWD
          source activate guts
          ls
          cd /tmp
          git clone https://github.com/singularityhub/guts
          cd guts
          pip install -e .
          cd docs
          pip install -r requirements.txt
          make html
          mv $root/.git _build/html/.git
          rm -rf $root
          mv _build/html $root
          cd $root
          touch .nojekyll
          ls

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
