name: Generate Container Guts
on:
  pull_request: []

jobs:
  generate-recipe:
    runs-on: ubuntu-latest
    name: ${{ inputs.docker_uri }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create conda environment
        run: conda create --quiet -c conda-forge --name guts

      - uses: actions/checkout@v3
      - name: Install Guts
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate guts
          pip install -e .
          echo "/usr/share/miniconda/bin" >> ${GITHUB_PATH}

      - name: Test Basic Guts
        uses: ./action/manifest
        with:
          image: "quay.io/autamus/clingo:5.5.1"

      - name: Filesystem Include
        uses: ./action/manifest
        with:
          image: "quay.io/autamus/clingo:5.5.1"
          include: fs

  generate-recipes:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:     
        image: ["ubuntu", "centos", "rockylinux:9.0", "alpine", "busybox"]

    name: Generate Matrix
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create conda environment
        run: conda create --quiet -c conda-forge --name guts

      - uses: actions/checkout@v3
      - name: Install Guts
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate guts
          pip install -e .
          echo "/usr/share/miniconda/bin" >> ${GITHUB_PATH}

      - name: Guts for ${{ matrix.image }}
        uses: ./action/manifest
        with:
          image: ${{ matrix.image }}
          outfile: ${{ matrix.image }}.json
      - name: View Output
        run: cat ${{ matrix.image }}.json
