name: Generate Container Yaml
on:
  pull_request: []
  workflow_dispatch: 
    inputs:
      docker_uri:
        description: 'Docker identifier to generate recipe for'
        required: true
        default: "quay.io/autamus/clingo:5.5.1"
jobs:
  generate-recipe:
    if: (inputs.docker_uri != '')
    runs-on: ubuntu-latest
    permissions:
      packages: read
    name: ${{ inputs.docker_uri }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Guts for ${{ inputs.docker_uri }}
        uses: ./manifest
        with:
          image: ${{ inputs.docker_uri }}

  generate-recipes:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      max-parallel: 4
      matrix:
        image: ["ubuntu", "centos", "rockylinux", "alpine", "busybox"]

    name: Generate Matrix
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Guts for ${{ inputs.docker_uri }}
        uses: ./manifest
        with:
          image: ${{ matrix.image }}
          outfile: ${{ matrix.image }}.json
      - name: View Output
        run: cat ${{ matix.image }}.json

